server:
  port: 8080
  shutdown: graceful

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
  web:
    resources:
      add-mappings: false
  sql:
    init:
      platform: mysql