spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skeleton?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: skeleton
    password: password4skeleton
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
  writer-with-default-pretty-printer: true

properties:
  passwordExpiration: 7
